// 汉字闯关游戏 - 1600个常见汉字数据库
// 按难度分为160关，每关10个汉字
// 每个汉字包含：字、拼音、释义、分类、类别emoji

const HANZI_DATA = [
  // ===== 第1关：数字基础 =====
  { char: '一', pinyin: 'yī', meaning: '数字，最小的正整数', category: '数字', emoji: '🔢' },
  { char: '二', pinyin: 'èr', meaning: '数字，一加一', category: '数字', emoji: '🔢' },
  { char: '三', pinyin: 'sān', meaning: '数字，二加一', category: '数字', emoji: '🔢' },
  { char: '四', pinyin: 'sì', meaning: '数字，三加一', category: '数字', emoji: '🔢' },
  { char: '五', pinyin: 'wǔ', meaning: '数字，四加一', category: '数字', emoji: '🔢' },
  { char: '六', pinyin: 'liù', meaning: '数字，五加一', category: '数字', emoji: '🔢' },
  { char: '七', pinyin: 'qī', meaning: '数字，六加一', category: '数字', emoji: '🔢' },
  { char: '八', pinyin: 'bā', meaning: '数字，七加一', category: '数字', emoji: '🔢' },
  { char: '九', pinyin: 'jiǔ', meaning: '数字，八加一', category: '数字', emoji: '🔢' },
  { char: '十', pinyin: 'shí', meaning: '数字，九加一', category: '数字', emoji: '🔢' },

  // ===== 第2关：简单汉字1 =====
  { char: '大', pinyin: 'dà', meaning: '形容体积、面积等很大', category: '形容', emoji: '📐' },
  { char: '小', pinyin: 'xiǎo', meaning: '形容体积、面积等很小', category: '形容', emoji: '📐' },
  { char: '人', pinyin: 'rén', meaning: '指人类，我们都是人', category: '人物', emoji: '🧑' },
  { char: '口', pinyin: 'kǒu', meaning: '嘴巴，用来吃饭和说话', category: '身体', emoji: '👄' },
  { char: '手', pinyin: 'shǒu', meaning: '手，用来拿东西和做事', category: '身体', emoji: '✋' },
  { char: '目', pinyin: 'mù', meaning: '眼睛，用来看东西', category: '身体', emoji: '👁️' },
  { char: '耳', pinyin: 'ěr', meaning: '耳朵，用来听声音', category: '身体', emoji: '👂' },
  { char: '足', pinyin: 'zú', meaning: '脚，用来走路和跑步', category: '身体', emoji: '🦶' },
  { char: '头', pinyin: 'tóu', meaning: '身体最上面的部分', category: '身体', emoji: '🗣️' },
  { char: '心', pinyin: 'xīn', meaning: '心脏，也指思想和感情', category: '身体', emoji: '❤️' },

  // ===== 第3关：自然现象 =====
  { char: '日', pinyin: 'rì', meaning: '太阳，天空中发光发热的星体', category: '自然', emoji: '☀️' },
  { char: '月', pinyin: 'yuè', meaning: '月亮，夜空中发亮的天体', category: '自然', emoji: '🌙' },
  { char: '星', pinyin: 'xīng', meaning: '星星，夜空中闪烁的光点', category: '自然', emoji: '⭐' },
  { char: '天', pinyin: 'tiān', meaning: '天空，头顶上面的空间', category: '自然', emoji: '🌤️' },
  { char: '风', pinyin: 'fēng', meaning: '空气流动形成风', category: '自然', emoji: '💨' },
  { char: '雨', pinyin: 'yǔ', meaning: '从天上落下的水滴', category: '天气', emoji: '🌧️' },
  { char: '雪', pinyin: 'xuě', meaning: '冬天从天上飘落的白色冰晶', category: '天气', emoji: '❄️' },
  { char: '云', pinyin: 'yún', meaning: '天空中飘着的白色水汽', category: '自然', emoji: '☁️' },
  { char: '火', pinyin: 'huǒ', meaning: '燃烧产生的光和热', category: '自然', emoji: '🔥' },
  { char: '水', pinyin: 'shuǐ', meaning: '无色透明的液体，生命之源', category: '自然', emoji: '💧' },

  // ===== 第4关：动物 =====
  { char: '牛', pinyin: 'niú', meaning: '能耕田的大型动物', category: '动物', emoji: '🐄' },
  { char: '马', pinyin: 'mǎ', meaning: '能骑跑的动物', category: '动物', emoji: '🐴' },
  { char: '羊', pinyin: 'yáng', meaning: '有角的温顺动物，毛可以织衣', category: '动物', emoji: '🐑' },
  { char: '鸟', pinyin: 'niǎo', meaning: '有翅膀会飞的动物', category: '动物', emoji: '🐦' },
  { char: '鱼', pinyin: 'yú', meaning: '生活在水里的动物', category: '动物', emoji: '🐟' },
  { char: '虫', pinyin: 'chóng', meaning: '小虫子，蚂蚁、蝴蝶都是虫', category: '动物', emoji: '🐛' },
  { char: '龙', pinyin: 'lóng', meaning: '中国传说中的神兽', category: '动物', emoji: '🐉' },
  { char: '猫', pinyin: 'māo', meaning: '常见的宠物，会捉老鼠', category: '动物', emoji: '🐱' },
  { char: '狗', pinyin: 'gǒu', meaning: '人类忠实的朋友，会看家', category: '动物', emoji: '🐶' },
  { char: '兔', pinyin: 'tù', meaning: '有长耳朵、爱吃萝卜的动物', category: '动物', emoji: '🐰' },

  // ===== 第5关：植物 =====
  { char: '木', pinyin: 'mù', meaning: '树木，砍下来可以做家具', category: '植物', emoji: '🌳' },
  { char: '林', pinyin: 'lín', meaning: '很多树在一起就是树林', category: '植物', emoji: '🌲' },
  { char: '田', pinyin: 'tián', meaning: '种庄稼的土地', category: '自然', emoji: '🌾' },
  { char: '土', pinyin: 'tǔ', meaning: '泥土，地面上松软的物质', category: '自然', emoji: '🟤' },
  { char: '山', pinyin: 'shān', meaning: '地面上高起的部分', category: '自然', emoji: '⛰️' },
  { char: '石', pinyin: 'shí', meaning: '坚硬的矿物，可盖房子', category: '自然', emoji: '🪨' },
  { char: '竹', pinyin: 'zhú', meaning: '中空的植物，熊猫爱吃', category: '植物', emoji: '🎋' },
  { char: '米', pinyin: 'mǐ', meaning: '稻谷去壳后就是米，可煮饭', category: '食物', emoji: '🍚' },
  { char: '瓜', pinyin: 'guā', meaning: '蔓生植物的果实，如西瓜', category: '植物', emoji: '🍉' },
  { char: '果', pinyin: 'guǒ', meaning: '植物结出的可以吃的部分', category: '植物', emoji: '🍎' },

  // ===== 第6关：方位与空间 =====
  { char: '上', pinyin: 'shàng', meaning: '位置在高处', category: '方位', emoji: '⬆️' },
  { char: '下', pinyin: 'xià', meaning: '位置在低处', category: '方位', emoji: '⬇️' },
  { char: '左', pinyin: 'zuǒ', meaning: '面向前方时的左手边', category: '方位', emoji: '⬅️' },
  { char: '右', pinyin: 'yòu', meaning: '面向前方时的右手边', category: '方位', emoji: '➡️' },
  { char: '中', pinyin: 'zhōng', meaning: '中间，里面', category: '方位', emoji: '🎯' },
  { char: '前', pinyin: 'qián', meaning: '面对的方向，前面', category: '方位', emoji: '🔝' },
  { char: '后', pinyin: 'hòu', meaning: '背对的方向，后面', category: '方位', emoji: '🔚' },
  { char: '里', pinyin: 'lǐ', meaning: '里面，内部', category: '方位', emoji: '🏠' },
  { char: '外', pinyin: 'wài', meaning: '外面，外部', category: '方位', emoji: '🌐' },
  { char: '东', pinyin: 'dōng', meaning: '太阳升起的方向', category: '方位', emoji: '🌅' },

  // ===== 第7关：家庭成员 =====
  { char: '父', pinyin: 'fù', meaning: '爸爸，父亲', category: '人物', emoji: '👨' },
  { char: '母', pinyin: 'mǔ', meaning: '妈妈，母亲', category: '人物', emoji: '👩' },
  { char: '子', pinyin: 'zǐ', meaning: '孩子，儿子', category: '人物', emoji: '👦' },
  { char: '女', pinyin: 'nǚ', meaning: '女性，女儿', category: '人物', emoji: '👧' },
  { char: '兄', pinyin: 'xiōng', meaning: '哥哥，比自己大的兄弟', category: '人物', emoji: '👦' },
  { char: '弟', pinyin: 'dì', meaning: '弟弟，比自己小的兄弟', category: '人物', emoji: '👦' },
  { char: '姐', pinyin: 'jiě', meaning: '姐姐，比自己大的姐妹', category: '人物', emoji: '👧' },
  { char: '妹', pinyin: 'mèi', meaning: '妹妹，比自己小的姐妹', category: '人物', emoji: '👧' },
  { char: '爷', pinyin: 'yé', meaning: '爷爷，祖父', category: '人物', emoji: '👴' },
  { char: '奶', pinyin: 'nǎi', meaning: '奶奶，也指牛奶', category: '人物', emoji: '👵' },

  // ===== 第8关：常用动词1 =====
  { char: '来', pinyin: 'lái', meaning: '从别的地方到这里', category: '动作', emoji: '🏃' },
  { char: '去', pinyin: 'qù', meaning: '从这里到别的地方', category: '动作', emoji: '🚶' },
  { char: '走', pinyin: 'zǒu', meaning: '用脚移动身体', category: '动作', emoji: '🚶' },
  { char: '跑', pinyin: 'pǎo', meaning: '快速地用脚移动', category: '动作', emoji: '🏃' },
  { char: '看', pinyin: 'kàn', meaning: '用眼睛注视', category: '动作', emoji: '👀' },
  { char: '听', pinyin: 'tīng', meaning: '用耳朵感受声音', category: '动作', emoji: '👂' },
  { char: '说', pinyin: 'shuō', meaning: '用嘴巴表达想法', category: '动作', emoji: '🗣️' },
  { char: '吃', pinyin: 'chī', meaning: '把食物放进嘴里咽下', category: '动作', emoji: '🍽️' },
  { char: '喝', pinyin: 'hē', meaning: '把液体咽下去', category: '动作', emoji: '🥤' },
  { char: '睡', pinyin: 'shuì', meaning: '闭上眼睛休息', category: '动作', emoji: '😴' },

  // ===== 第9关：常用动词2 =====
  { char: '打', pinyin: 'dǎ', meaning: '用手敲击或拍打', category: '动作', emoji: '👊' },
  { char: '拿', pinyin: 'ná', meaning: '用手取东西', category: '动作', emoji: '✊' },
  { char: '写', pinyin: 'xiě', meaning: '用笔把字写在纸上', category: '动作', emoji: '✍️' },
  { char: '读', pinyin: 'dú', meaning: '看着文字念出来', category: '动作', emoji: '📖' },
  { char: '学', pinyin: 'xué', meaning: '学习，获取知识', category: '动作', emoji: '📚' },
  { char: '问', pinyin: 'wèn', meaning: '提出问题，想知道答案', category: '动作', emoji: '❓' },
  { char: '答', pinyin: 'dá', meaning: '回答问题', category: '动作', emoji: '💬' },
  { char: '开', pinyin: 'kāi', meaning: '把关着的东西打开', category: '动作', emoji: '🔓' },
  { char: '关', pinyin: 'guān', meaning: '把开着的东西合上', category: '动作', emoji: '🔒' },
  { char: '给', pinyin: 'gěi', meaning: '把东西交给别人', category: '动作', emoji: '🤲' },

  // ===== 第10关：颜色与描述 =====
  { char: '白', pinyin: 'bái', meaning: '像雪一样的颜色', category: '颜色', emoji: '⚪' },
  { char: '红', pinyin: 'hóng', meaning: '像血和太阳的颜色', category: '颜色', emoji: '🔴' },
  { char: '黑', pinyin: 'hēi', meaning: '像煤炭和夜晚的颜色', category: '颜色', emoji: '⚫' },
  { char: '青', pinyin: 'qīng', meaning: '绿色或蓝色', category: '颜色', emoji: '🟢' },
  { char: '多', pinyin: 'duō', meaning: '数量大', category: '形容', emoji: '🔢' },
  { char: '少', pinyin: 'shǎo', meaning: '数量小', category: '形容', emoji: '🔢' },
  { char: '高', pinyin: 'gāo', meaning: '从下到上距离大', category: '形容', emoji: '📏' },
  { char: '长', pinyin: 'cháng', meaning: '两端距离大', category: '形容', emoji: '📏' },
  { char: '好', pinyin: 'hǎo', meaning: '让人满意的，不错的', category: '形容', emoji: '👍' },
  { char: '美', pinyin: 'měi', meaning: '好看，漂亮', category: '形容', emoji: '✨' },

  // ===== 第11关：日常生活 =====
  { char: '书', pinyin: 'shū', meaning: '装订好的纸，用来阅读', category: '物品', emoji: '📖' },
  { char: '笔', pinyin: 'bǐ', meaning: '写字画画的工具', category: '物品', emoji: '🖊️' },
  { char: '纸', pinyin: 'zhǐ', meaning: '写字、画画用的薄片', category: '物品', emoji: '📄' },
  { char: '车', pinyin: 'chē', meaning: '有轮子的交通工具', category: '交通', emoji: '🚗' },
  { char: '船', pinyin: 'chuán', meaning: '在水上航行的交通工具', category: '交通', emoji: '🚢' },
  { char: '门', pinyin: 'mén', meaning: '进出房间的通道', category: '建筑', emoji: '🚪' },
  { char: '窗', pinyin: 'chuāng', meaning: '墙上用来透光的开口', category: '建筑', emoji: '🪟' },
  { char: '床', pinyin: 'chuáng', meaning: '睡觉用的家具', category: '物品', emoji: '🛏️' },
  { char: '桌', pinyin: 'zhuō', meaning: '有平坦桌面的家具', category: '物品', emoji: '🪑' },
  { char: '椅', pinyin: 'yǐ', meaning: '可以坐的家具', category: '物品', emoji: '🪑' },

  // ===== 第12关：时间 =====
  { char: '年', pinyin: 'nián', meaning: '地球绕太阳一圈的时间', category: '时间', emoji: '📅' },
  { char: '今', pinyin: 'jīn', meaning: '现在，今天', category: '时间', emoji: '📅' },
  { char: '明', pinyin: 'míng', meaning: '明天，也指明亮', category: '时间', emoji: '🔆' },
  { char: '早', pinyin: 'zǎo', meaning: '早晨，天刚亮的时候', category: '时间', emoji: '🌅' },
  { char: '晚', pinyin: 'wǎn', meaning: '晚上，天黑以后', category: '时间', emoji: '🌙' },
  { char: '春', pinyin: 'chūn', meaning: '春季，万物生长的季节', category: '时间', emoji: '🌸' },
  { char: '夏', pinyin: 'xià', meaning: '夏季，最热的季节', category: '时间', emoji: '☀️' },
  { char: '秋', pinyin: 'qiū', meaning: '秋季，丰收的季节', category: '时间', emoji: '🍂' },
  { char: '冬', pinyin: 'dōng', meaning: '冬季，最冷的季节', category: '时间', emoji: '❄️' },
  { char: '时', pinyin: 'shí', meaning: '时间，钟点', category: '时间', emoji: '⏰' },

  // ===== 第13关：食物1 =====
  { char: '米', pinyin: 'mǐ', meaning: '大米，主食来源', category: '食物', emoji: '🍚' },
  { char: '面', pinyin: 'miàn', meaning: '面粉做的食品，如面条', category: '食物', emoji: '🍜' },
  { char: '菜', pinyin: 'cài', meaning: '可以做菜的植物', category: '食物', emoji: '🥬' },
  { char: '肉', pinyin: 'ròu', meaning: '动物的肉，如猪肉牛肉', category: '食物', emoji: '🥩' },
  { char: '茶', pinyin: 'chá', meaning: '用茶叶泡的饮品', category: '食物', emoji: '🍵' },
  { char: '酒', pinyin: 'jiǔ', meaning: '用粮食酿成的饮品', category: '食物', emoji: '🍶' },
  { char: '糖', pinyin: 'táng', meaning: '甜味的食品', category: '食物', emoji: '🍬' },
  { char: '盐', pinyin: 'yán', meaning: '调味品，做菜不可缺少', category: '食物', emoji: '🧂' },
  { char: '蛋', pinyin: 'dàn', meaning: '鸡鸭等产的卵', category: '食物', emoji: '🥚' },
  { char: '豆', pinyin: 'dòu', meaning: '豆类植物，如黄豆绿豆', category: '食物', emoji: '🫘' },

  // ===== 第14关：身体部位 =====
  { char: '牙', pinyin: 'yá', meaning: '牙齿，用来咬食物', category: '身体', emoji: '🦷' },
  { char: '舌', pinyin: 'shé', meaning: '舌头，尝味道和说话', category: '身体', emoji: '👅' },
  { char: '发', pinyin: 'fà', meaning: '头发，长在头上', category: '身体', emoji: '💇' },
  { char: '背', pinyin: 'bèi', meaning: '身体后面的部分', category: '身体', emoji: '🔙' },
  { char: '骨', pinyin: 'gǔ', meaning: '骨骼，支撑身体的硬组织', category: '身体', emoji: '🦴' },
  { char: '血', pinyin: 'xuè', meaning: '在血管里流动的红色液体', category: '身体', emoji: '🩸' },
  { char: '指', pinyin: 'zhǐ', meaning: '手指，手上的五个分支', category: '身体', emoji: '☝️' },
  { char: '皮', pinyin: 'pí', meaning: '皮肤，身体表面的保护层', category: '身体', emoji: '🖐️' },
  { char: '毛', pinyin: 'máo', meaning: '细小的毛发', category: '自然', emoji: '🧶' },
  { char: '角', pinyin: 'jiǎo', meaning: '动物的角，如牛角羊角', category: '身体', emoji: '🐂' },

  // ===== 第15关：学习用品 =====
  { char: '字', pinyin: 'zì', meaning: '汉字，记录语言的符号', category: '学习', emoji: '📝' },
  { char: '词', pinyin: 'cí', meaning: '有意义的语言单位', category: '学习', emoji: '📖' },
  { char: '句', pinyin: 'jù', meaning: '完整的句子', category: '学习', emoji: '✏️' },
  { char: '文', pinyin: 'wén', meaning: '文章、文化', category: '学习', emoji: '📄' },
  { char: '课', pinyin: 'kè', meaning: '课程，一节课的时间', category: '学习', emoji: '📚' },
  { char: '校', pinyin: 'xiào', meaning: '学校，学习的地方', category: '学习', emoji: '🏫' },
  { char: '师', pinyin: 'shī', meaning: '老师，教书育人的人', category: '人物', emoji: '👨‍🏫' },
  { char: '生', pinyin: 'shēng', meaning: '学生，学习的人', category: '人物', emoji: '👨‍🎓' },
  { char: '本', pinyin: 'běn', meaning: '本子，书写用的本册', category: '物品', emoji: '📓' },
  { char: '包', pinyin: 'bāo', meaning: '书包，装东西的袋子', category: '物品', emoji: '🎒' },

  // ===== 第16关：感觉和情绪 =====
  { char: '乐', pinyin: 'lè', meaning: '快乐，高兴', category: '情绪', emoji: '😊' },
  { char: '笑', pinyin: 'xiào', meaning: '开心时嘴角上扬', category: '情绪', emoji: '😄' },
  { char: '哭', pinyin: 'kū', meaning: '伤心时流眼泪', category: '情绪', emoji: '😢' },
  { char: '怕', pinyin: 'pà', meaning: '害怕，恐惧', category: '情绪', emoji: '😨' },
  { char: '爱', pinyin: 'ài', meaning: '喜欢，爱护', category: '情绪', emoji: '❤️' },
  { char: '恨', pinyin: 'hèn', meaning: '不喜欢，怨恨', category: '情绪', emoji: '😠' },
  { char: '喜', pinyin: 'xǐ', meaning: '欢喜，高兴', category: '情绪', emoji: '🥰' },
  { char: '怒', pinyin: 'nù', meaning: '生气，发怒', category: '情绪', emoji: '😡' },
  { char: '欢', pinyin: 'huān', meaning: '欢乐，开心', category: '情绪', emoji: '🎉' },
  { char: '愁', pinyin: 'chóu', meaning: '发愁，担忧', category: '情绪', emoji: '😟' },

  // ===== 第17关：衣物 =====
  { char: '衣', pinyin: 'yī', meaning: '衣服，穿在身上的', category: '物品', emoji: '👕' },
  { char: '裤', pinyin: 'kù', meaning: '裤子，穿在腿上的', category: '物品', emoji: '👖' },
  { char: '帽', pinyin: 'mào', meaning: '帽子，戴在头上的', category: '物品', emoji: '🎩' },
  { char: '鞋', pinyin: 'xié', meaning: '鞋子，穿在脚上的', category: '物品', emoji: '👟' },
  { char: '袜', pinyin: 'wà', meaning: '袜子，穿在脚上的针织品', category: '物品', emoji: '🧦' },
  { char: '带', pinyin: 'dài', meaning: '带子，腰带', category: '物品', emoji: '🎀' },
  { char: '布', pinyin: 'bù', meaning: '布料，做衣服的材料', category: '物品', emoji: '🧵' },
  { char: '丝', pinyin: 'sī', meaning: '蚕丝，光滑的天然纤维', category: '物品', emoji: '🧶' },
  { char: '金', pinyin: 'jīn', meaning: '黄金，贵重的金属', category: '物品', emoji: '🥇' },
  { char: '银', pinyin: 'yín', meaning: '白银，白色的贵金属', category: '物品', emoji: '🥈' },

  // ===== 第18关：动作3 =====
  { char: '飞', pinyin: 'fēi', meaning: '在空中移动，像鸟一样', category: '动作', emoji: '🕊️' },
  { char: '游', pinyin: 'yóu', meaning: '在水中移动', category: '动作', emoji: '🏊' },
  { char: '爬', pinyin: 'pá', meaning: '手脚并用向前移动', category: '动作', emoji: '🧗' },
  { char: '跳', pinyin: 'tiào', meaning: '两脚离地向上弹起', category: '动作', emoji: '🤸' },
  { char: '坐', pinyin: 'zuò', meaning: '屁股坐在东西上', category: '动作', emoji: '🪑' },
  { char: '站', pinyin: 'zhàn', meaning: '用脚支撑身体直立', category: '动作', emoji: '🧍' },
  { char: '拉', pinyin: 'lā', meaning: '用力往自己方向拖', category: '动作', emoji: '🤝' },
  { char: '推', pinyin: 'tuī', meaning: '用力使物体移动', category: '动作', emoji: '👐' },
  { char: '提', pinyin: 'tí', meaning: '用手从下往上拿', category: '动作', emoji: '✋' },
  { char: '抱', pinyin: 'bào', meaning: '用手臂围住', category: '动作', emoji: '🤗' },

  // ===== 第19关：常用名词1 =====
  { char: '家', pinyin: 'jiā', meaning: '住的地方，家庭', category: '场所', emoji: '🏠' },
  { char: '国', pinyin: 'guó', meaning: '国家，我们是中国', category: '场所', emoji: '🇨🇳' },
  { char: '城', pinyin: 'chéng', meaning: '城市，很多人住的地方', category: '场所', emoji: '🏙️' },
  { char: '路', pinyin: 'lù', meaning: '道路，行走的通道', category: '场所', emoji: '🛣️' },
  { char: '河', pinyin: 'hé', meaning: '河流，水流过的地方', category: '自然', emoji: '🏞️' },
  { char: '海', pinyin: 'hǎi', meaning: '大海，很大的水域', category: '自然', emoji: '🌊' },
  { char: '湖', pinyin: 'hú', meaning: '湖泊，四面被陆地围着的水', category: '自然', emoji: '🏞️' },
  { char: '桥', pinyin: 'qiáo', meaning: '架在河上的通道', category: '建筑', emoji: '🌉' },
  { char: '店', pinyin: 'diàn', meaning: '商店，买东西的地方', category: '场所', emoji: '🏪' },
  { char: '园', pinyin: 'yuán', meaning: '花园，种花草的地方', category: '场所', emoji: '🌺' },

  // ===== 第20关：常用形容词2 =====
  { char: '冷', pinyin: 'lěng', meaning: '温度低，感觉凉', category: '形容', emoji: '🥶' },
  { char: '热', pinyin: 'rè', meaning: '温度高，感觉烫', category: '形容', emoji: '🥵' },
  { char: '新', pinyin: 'xīn', meaning: '刚出现的，不是旧的', category: '形容', emoji: '✨' },
  { char: '旧', pinyin: 'jiù', meaning: '用了很久的，不新的', category: '形容', emoji: '📦' },
  { char: '快', pinyin: 'kuài', meaning: '速度高，很快', category: '形容', emoji: '⚡' },
  { char: '慢', pinyin: 'màn', meaning: '速度低，不快', category: '形容', emoji: '🐌' },
  { char: '远', pinyin: 'yuǎn', meaning: '距离大，很远', category: '形容', emoji: '🔭' },
  { char: '近', pinyin: 'jìn', meaning: '距离小，很近', category: '形容', emoji: '📍' },
  { char: '重', pinyin: 'zhòng', meaning: '分量大，很沉', category: '形容', emoji: '🏋️' },
  { char: '轻', pinyin: 'qīng', meaning: '分量小，不沉', category: '形容', emoji: '🪶' },

  // ===== 第21-40关：进阶常用字 =====
  { char: '花', pinyin: 'huā', meaning: '植物的器官，有各种颜色', category: '植物', emoji: '🌸' },
  { char: '草', pinyin: 'cǎo', meaning: '矮小的绿色植物', category: '植物', emoji: '🌱' },
  { char: '叶', pinyin: 'yè', meaning: '植物进行光合作用的薄片', category: '植物', emoji: '🍃' },
  { char: '根', pinyin: 'gēn', meaning: '植物长在土里的部分', category: '植物', emoji: '🌱' },
  { char: '树', pinyin: 'shù', meaning: '有树干和树叶的植物', category: '植物', emoji: '🌳' },
  { char: '光', pinyin: 'guāng', meaning: '光线，照亮东西的', category: '自然', emoji: '💡' },
  { char: '电', pinyin: 'diàn', meaning: '电能，让电器工作的能量', category: '自然', emoji: '⚡' },
  { char: '力', pinyin: 'lì', meaning: '力量，力气', category: '形容', emoji: '💪' },
  { char: '王', pinyin: 'wáng', meaning: '国王，一国之主', category: '人物', emoji: '👑' },
  { char: '正', pinyin: 'zhèng', meaning: '对的，正确的', category: '形容', emoji: '✅' },

  { char: '平', pinyin: 'píng', meaning: '没有高低起伏的', category: '形容', emoji: '↔️' },
  { char: '安', pinyin: 'ān', meaning: '安全，平安', category: '形容', emoji: '🛡️' },
  { char: '和', pinyin: 'hé', meaning: '和平，和睦', category: '形容', emoji: '☮️' },
  { char: '同', pinyin: 'tóng', meaning: '一样，相同', category: '形容', emoji: '🔄' },
  { char: '全', pinyin: 'quán', meaning: '全部，完整', category: '形容', emoji: '💯' },
  { char: '半', pinyin: 'bàn', meaning: '一半，二分之一', category: '数字', emoji: '➗' },
  { char: '百', pinyin: 'bǎi', meaning: '数字一百', category: '数字', emoji: '💯' },
  { char: '千', pinyin: 'qiān', meaning: '数字一千', category: '数字', emoji: '🔢' },
  { char: '万', pinyin: 'wàn', meaning: '数字一万', category: '数字', emoji: '🔢' },
  { char: '元', pinyin: 'yuán', meaning: '钱的单位，一元钱', category: '数字', emoji: '💰' },

  { char: '回', pinyin: 'huí', meaning: '返回，回来', category: '动作', emoji: '🔄' },
  { char: '过', pinyin: 'guò', meaning: '从上面经过', category: '动作', emoji: '➡️' },
  { char: '起', pinyin: 'qǐ', meaning: '由坐躺变站立，开始', category: '动作', emoji: '⬆️' },
  { char: '出', pinyin: 'chū', meaning: '从里面到外面', category: '动作', emoji: '🚪' },
  { char: '入', pinyin: 'rù', meaning: '从外面到里面', category: '动作', emoji: '🚪' },
  { char: '到', pinyin: 'dào', meaning: '到达某个地方', category: '动作', emoji: '🏁' },
  { char: '在', pinyin: 'zài', meaning: '存在于某个地方', category: '形容', emoji: '📍' },
  { char: '有', pinyin: 'yǒu', meaning: '拥有，存在', category: '形容', emoji: '✅' },
  { char: '是', pinyin: 'shì', meaning: '表示判断，等于', category: '形容', emoji: '➡️' },
  { char: '不', pinyin: 'bù', meaning: '表示否定，不是', category: '形容', emoji: '❌' },

  { char: '想', pinyin: 'xiǎng', meaning: '思考，考虑', category: '动作', emoji: '💭' },
  { char: '会', pinyin: 'huì', meaning: '能够，懂得', category: '形容', emoji: '🧠' },
  { char: '能', pinyin: 'néng', meaning: '有能力做到', category: '形容', emoji: '💪' },
  { char: '知', pinyin: 'zhī', meaning: '知道，了解', category: '动作', emoji: '🧠' },
  { char: '觉', pinyin: 'jué', meaning: '感觉，发觉', category: '动作', emoji: '💡' },
  { char: '见', pinyin: 'jiàn', meaning: '看到，看见', category: '动作', emoji: '👀' },
  { char: '用', pinyin: 'yòng', meaning: '使用，利用', category: '动作', emoji: '🔧' },
  { char: '可', pinyin: 'kě', meaning: '可以，能够', category: '形容', emoji: '✅' },
  { char: '要', pinyin: 'yào', meaning: '需要，想要', category: '动作', emoji: '🙋' },
  { char: '做', pinyin: 'zuò', meaning: '制造，进行某事', category: '动作', emoji: '🔨' },

  { char: '工', pinyin: 'gōng', meaning: '工作，做工', category: '社会', emoji: '👷' },
  { char: '农', pinyin: 'nóng', meaning: '农业，种地的', category: '社会', emoji: '👨‍🌾' },
  { char: '商', pinyin: 'shāng', meaning: '商业，做买卖的', category: '社会', emoji: '🏪' },
  { char: '兵', pinyin: 'bīng', meaning: '士兵，当兵的人', category: '社会', emoji: '🪖' },
  { char: '医', pinyin: 'yī', meaning: '医生，看病的人', category: '人物', emoji: '👨‍⚕️' },
  { char: '歌', pinyin: 'gē', meaning: '歌曲，可以唱的', category: '文艺', emoji: '🎵' },
  { char: '画', pinyin: 'huà', meaning: '图画，画的画', category: '文艺', emoji: '🎨' },
  { char: '音', pinyin: 'yīn', meaning: '声音，音乐', category: '文艺', emoji: '🔊' },
  { char: '色', pinyin: 'sè', meaning: '颜色，色彩', category: '形容', emoji: '🎨' },
  { char: '声', pinyin: 'shēng', meaning: '声音，发出的声响', category: '形容', emoji: '📣' },

  { char: '气', pinyin: 'qì', meaning: '空气，气体', category: '自然', emoji: '💨' },
  { char: '味', pinyin: 'wèi', meaning: '味道，滋味', category: '形容', emoji: '👅' },
  { char: '香', pinyin: 'xiāng', meaning: '气味好闻', category: '形容', emoji: '🌸' },
  { char: '甜', pinyin: 'tián', meaning: '像糖一样的味道', category: '形容', emoji: '🍬' },
  { char: '苦', pinyin: 'kǔ', meaning: '像药一样的味道', category: '形容', emoji: '💊' },
  { char: '酸', pinyin: 'suān', meaning: '像柠檬一样的味道', category: '形容', emoji: '🍋' },
  { char: '辣', pinyin: 'là', meaning: '像辣椒一样的味道', category: '形容', emoji: '🌶️' },
  { char: '鲜', pinyin: 'xiān', meaning: '新鲜，味道鲜美', category: '形容', emoji: '✨' },
  { char: '干', pinyin: 'gān', meaning: '没有水分的', category: '形容', emoji: '🏜️' },
  { char: '湿', pinyin: 'shī', meaning: '含有水分的', category: '形容', emoji: '💧' },

  // ===== 第41-60关：更多常用字 =====
  { char: '真', pinyin: 'zhēn', meaning: '真实的，不是假的', category: '形容', emoji: '💯' },
  { char: '假', pinyin: 'jiǎ', meaning: '不真实的，人造的', category: '形容', emoji: '🎭' },
  { char: '对', pinyin: 'duì', meaning: '正确，没错', category: '形容', emoji: '✅' },
  { char: '错', pinyin: 'cuò', meaning: '不正确，错误的', category: '形容', emoji: '❌' },
  { char: '难', pinyin: 'nán', meaning: '不容易做到', category: '形容', emoji: '😤' },
  { char: '易', pinyin: 'yì', meaning: '容易做到', category: '形容', emoji: '😊' },
  { char: '深', pinyin: 'shēn', meaning: '从上到下距离大', category: '形容', emoji: '🌊' },
  { char: '浅', pinyin: 'qiǎn', meaning: '从上到下距离小', category: '形容', emoji: '🏖️' },
  { char: '宽', pinyin: 'kuān', meaning: '横向距离大', category: '形容', emoji: '↔️' },
  { char: '窄', pinyin: 'zhǎi', meaning: '横向距离小', category: '形容', emoji: '📏' },

  { char: '先', pinyin: 'xiān', meaning: '时间或次序在前', category: '时间', emoji: '1️⃣' },
  { char: '后', pinyin: 'hòu', meaning: '时间或次序在后', category: '时间', emoji: '🔚' },
  { char: '老', pinyin: 'lǎo', meaning: '年纪大，不年轻', category: '形容', emoji: '👴' },
  { char: '少', pinyin: 'shào', meaning: '年纪小，年轻', category: '形容', emoji: '👦' },
  { char: '男', pinyin: 'nán', meaning: '男性，男人', category: '人物', emoji: '👦' },
  { char: '公', pinyin: 'gōng', meaning: '公共的，大家的', category: '社会', emoji: '🏛️' },
  { char: '死', pinyin: 'sǐ', meaning: '生命结束', category: '形容', emoji: '⚠️' },
  { char: '活', pinyin: 'huó', meaning: '有生命的，活着', category: '形容', emoji: '🌱' },
  { char: '亮', pinyin: 'liàng', meaning: '明亮，发光', category: '形容', emoji: '💡' },
  { char: '暗', pinyin: 'àn', meaning: '光线不足，黑暗', category: '形容', emoji: '🌑' },

  { char: '收', pinyin: 'shōu', meaning: '把散开的东西聚拢', category: '动作', emoji: '📥' },
  { char: '放', pinyin: 'fàng', meaning: '把东西搁置在某处', category: '动作', emoji: '📤' },
  { char: '送', pinyin: 'sòng', meaning: '把东西给人', category: '动作', emoji: '🎁' },
  { char: '接', pinyin: 'jiē', meaning: '收取别人给的东西', category: '动作', emoji: '🤝' },
  { char: '买', pinyin: 'mǎi', meaning: '花钱获取东西', category: '动作', emoji: '🛒' },
  { char: '卖', pinyin: 'mài', meaning: '出售东西换钱', category: '动作', emoji: '💰' },
  { char: '借', pinyin: 'jiè', meaning: '暂时使用别人的东西', category: '动作', emoji: '🤲' },
  { char: '还', pinyin: 'huán', meaning: '把借的东西归还', category: '动作', emoji: '🔄' },
  { char: '穿', pinyin: 'chuān', meaning: '把衣服鞋袜穿上', category: '动作', emoji: '👕' },
  { char: '戴', pinyin: 'dài', meaning: '把帽子等放在头上', category: '动作', emoji: '🎩' },

  { char: '种', pinyin: 'zhòng', meaning: '种植，播种', category: '动作', emoji: '🌱' },
  { char: '收', pinyin: 'shōu', meaning: '收割庄稼', category: '动作', emoji: '🌾' },
  { char: '住', pinyin: 'zhù', meaning: '居住，住在某处', category: '动作', emoji: '🏠' },
  { char: '行', pinyin: 'xíng', meaning: '可以，没问题', category: '形容', emoji: '👍' },
  { char: '停', pinyin: 'tíng', meaning: '停止不动', category: '动作', emoji: '🛑' },
  { char: '动', pinyin: 'dòng', meaning: '改变位置，行动', category: '动作', emoji: '🏃' },
  { char: '变', pinyin: 'biàn', meaning: '改变，变化', category: '动作', emoji: '🔄' },
  { char: '成', pinyin: 'chéng', meaning: '成功，变成', category: '动作', emoji: '🎯' },
  { char: '定', pinyin: 'dìng', meaning: '决定，确定', category: '动作', emoji: '📌' },
  { char: '算', pinyin: 'suàn', meaning: '计算，算数', category: '动作', emoji: '🧮' },

  { char: '数', pinyin: 'shù', meaning: '数目，数字', category: '数字', emoji: '🔢' },
  { char: '量', pinyin: 'liàng', meaning: '测量，数量', category: '形容', emoji: '📏' },
  { char: '度', pinyin: 'dù', meaning: '度数，程度', category: '形容', emoji: '🌡️' },
  { char: '形', pinyin: 'xíng', meaning: '形状，样子', category: '形容', emoji: '🔷' },
  { char: '体', pinyin: 'tǐ', meaning: '身体，物体', category: '身体', emoji: '🧍' },
  { char: '位', pinyin: 'wèi', meaning: '位置，座位', category: '形容', emoji: '📍' },
  { char: '号', pinyin: 'hào', meaning: '号码，编号', category: '数字', emoji: '🔢' },
  { char: '名', pinyin: 'míng', meaning: '名字，姓名', category: '社会', emoji: '📛' },
  { char: '地', pinyin: 'dì', meaning: '土地，地面', category: '自然', emoji: '🌍' },
  { char: '理', pinyin: 'lǐ', meaning: '道理，理由', category: '形容', emoji: '🧠' },

  // ===== 第61-80关：更高阶汉字 =====
  { char: '思', pinyin: 'sī', meaning: '思考，动脑筋', category: '动作', emoji: '💭' },
  { char: '念', pinyin: 'niàn', meaning: '想念，念书', category: '动作', emoji: '📖' },
  { char: '记', pinyin: 'jì', meaning: '记住，记忆', category: '动作', emoji: '🧠' },
  { char: '忘', pinyin: 'wàng', meaning: '不记得了', category: '动作', emoji: '❓' },
  { char: '认', pinyin: 'rèn', meaning: '认识，辨认', category: '动作', emoji: '👀' },
  { char: '识', pinyin: 'shí', meaning: '认识，知识', category: '动作', emoji: '📚' },
  { char: '懂', pinyin: 'dǒng', meaning: '理解，明白', category: '动作', emoji: '💡' },
  { char: '信', pinyin: 'xìn', meaning: '相信，信件', category: '动作', emoji: '✉️' },
  { char: '意', pinyin: 'yì', meaning: '意思，心意', category: '形容', emoji: '💭' },
  { char: '情', pinyin: 'qíng', meaning: '感情，情况', category: '情绪', emoji: '💝' },

  { char: '常', pinyin: 'cháng', meaning: '经常，常常', category: '形容', emoji: '🔄' },
  { char: '非', pinyin: 'fēi', meaning: '不是，不对', category: '形容', emoji: '❌' },
  { char: '但', pinyin: 'dàn', meaning: '但是，不过', category: '形容', emoji: '↩️' },
  { char: '如', pinyin: 'rú', meaning: '像，如同', category: '形容', emoji: '🔄' },
  { char: '其', pinyin: 'qí', meaning: '他的，那个', category: '形容', emoji: '👉' },
  { char: '所', pinyin: 'suǒ', meaning: '地方，所以', category: '形容', emoji: '📍' },
  { char: '之', pinyin: 'zhī', meaning: '的，到…去', category: '形容', emoji: '➡️' },
  { char: '这', pinyin: 'zhè', meaning: '这个，近指', category: '形容', emoji: '👉' },
  { char: '那', pinyin: 'nà', meaning: '那个，远指', category: '形容', emoji: '👈' },
  { char: '哪', pinyin: 'nǎ', meaning: '表示疑问，哪个', category: '形容', emoji: '❓' },

  { char: '谁', pinyin: 'shuí', meaning: '问人的代词', category: '形容', emoji: '❓' },
  { char: '什', pinyin: 'shén', meaning: '什么，疑问词', category: '形容', emoji: '❓' },
  { char: '怎', pinyin: 'zěn', meaning: '怎么，怎样', category: '形容', emoji: '❓' },
  { char: '为', pinyin: 'wéi', meaning: '做，作为', category: '动作', emoji: '🛠️' },
  { char: '从', pinyin: 'cóng', meaning: '由，自，跟随', category: '形容', emoji: '➡️' },
  { char: '把', pinyin: 'bǎ', meaning: '拿，握住', category: '动作', emoji: '✊' },
  { char: '被', pinyin: 'bèi', meaning: '被动，覆盖', category: '形容', emoji: '🔙' },
  { char: '让', pinyin: 'ràng', meaning: '允许，让步', category: '动作', emoji: '🤝' },
  { char: '教', pinyin: 'jiāo', meaning: '教导，教育', category: '动作', emoji: '👨‍🏫' },
  { char: '讲', pinyin: 'jiǎng', meaning: '讲述，讲解', category: '动作', emoji: '🗣️' },

  { char: '议', pinyin: 'yì', meaning: '讨论，议论', category: '动作', emoji: '💬' },
  { char: '论', pinyin: 'lùn', meaning: '讨论，观点', category: '动作', emoji: '📝' },
  { char: '话', pinyin: 'huà', meaning: '话语，说的话', category: '学习', emoji: '💬' },
  { char: '语', pinyin: 'yǔ', meaning: '语言，说话', category: '学习', emoji: '🗣️' },
  { char: '言', pinyin: 'yán', meaning: '言语，说话', category: '学习', emoji: '💬' },
  { char: '诗', pinyin: 'shī', meaning: '诗歌，押韵的文字', category: '文艺', emoji: '📜' },
  { char: '故', pinyin: 'gù', meaning: '故事，缘故', category: '学习', emoji: '📖' },
  { char: '事', pinyin: 'shì', meaning: '事情，事件', category: '社会', emoji: '📋' },
  { char: '物', pinyin: 'wù', meaning: '东西，物品', category: '物品', emoji: '📦' },
  { char: '景', pinyin: 'jǐng', meaning: '风景，景色', category: '自然', emoji: '🌄' },

  { char: '世', pinyin: 'shì', meaning: '世界，世代', category: '社会', emoji: '🌍' },
  { char: '界', pinyin: 'jiè', meaning: '界限，世界', category: '社会', emoji: '🗺️' },
  { char: '区', pinyin: 'qū', meaning: '区域，地区', category: '场所', emoji: '📍' },
  { char: '段', pinyin: 'duàn', meaning: '段落，一段', category: '形容', emoji: '📏' },
  { char: '层', pinyin: 'céng', meaning: '层次，楼层', category: '形容', emoji: '🏢' },
  { char: '级', pinyin: 'jí', meaning: '等级，级别', category: '形容', emoji: '📊' },
  { char: '类', pinyin: 'lèi', meaning: '种类，类别', category: '形容', emoji: '📂' },
  { char: '型', pinyin: 'xíng', meaning: '类型，模型', category: '形容', emoji: '📊' },
  { char: '样', pinyin: 'yàng', meaning: '样子，模样', category: '形容', emoji: '👀' },
  { char: '式', pinyin: 'shì', meaning: '样式，方式', category: '形容', emoji: '📝' },

  // ===== 第81-100关 =====
  { char: '持', pinyin: 'chí', meaning: '拿着，坚持', category: '动作', emoji: '✊' },
  { char: '保', pinyin: 'bǎo', meaning: '保护，保持', category: '动作', emoji: '🛡️' },
  { char: '管', pinyin: 'guǎn', meaning: '管理，负责', category: '动作', emoji: '📋' },
  { char: '查', pinyin: 'chá', meaning: '检查，查看', category: '动作', emoji: '🔍' },
  { char: '检', pinyin: 'jiǎn', meaning: '检验，检查', category: '动作', emoji: '🔍' },
  { char: '验', pinyin: 'yàn', meaning: '实验，验证', category: '动作', emoji: '🔬' },
  { char: '考', pinyin: 'kǎo', meaning: '考试，考查', category: '学习', emoji: '📝' },
  { char: '试', pinyin: 'shì', meaning: '尝试，考试', category: '动作', emoji: '✍️' },
  { char: '练', pinyin: 'liàn', meaning: '练习，训练', category: '动作', emoji: '💪' },
  { char: '习', pinyin: 'xí', meaning: '学习，复习', category: '动作', emoji: '📚' },

  { char: '参', pinyin: 'cān', meaning: '参加，参与', category: '动作', emoji: '🤝' },
  { char: '加', pinyin: 'jiā', meaning: '增加，加上', category: '动作', emoji: '➕' },
  { char: '减', pinyin: 'jiǎn', meaning: '减少，减去', category: '动作', emoji: '➖' },
  { char: '乘', pinyin: 'chéng', meaning: '乘法，骑坐', category: '动作', emoji: '✖️' },
  { char: '除', pinyin: 'chú', meaning: '除法，去除', category: '动作', emoji: '➗' },
  { char: '比', pinyin: 'bǐ', meaning: '比较，对比', category: '动作', emoji: '⚖️' },
  { char: '较', pinyin: 'jiào', meaning: '比较，较量', category: '动作', emoji: '⚖️' },
  { char: '最', pinyin: 'zuì', meaning: '最高程度，顶', category: '形容', emoji: '🏆' },
  { char: '更', pinyin: 'gèng', meaning: '更加，更进一步', category: '形容', emoji: '⬆️' },
  { char: '已', pinyin: 'yǐ', meaning: '已经，发生过', category: '形容', emoji: '✅' },

  { char: '未', pinyin: 'wèi', meaning: '还没有，未来', category: '形容', emoji: '🔜' },
  { char: '将', pinyin: 'jiāng', meaning: '将要，将来', category: '时间', emoji: '🔜' },
  { char: '曾', pinyin: 'céng', meaning: '曾经，以前', category: '时间', emoji: '🔙' },
  { char: '该', pinyin: 'gāi', meaning: '应该，应当', category: '形容', emoji: '📝' },
  { char: '须', pinyin: 'xū', meaning: '必须，须要', category: '形容', emoji: '⚠️' },
  { char: '需', pinyin: 'xū', meaning: '需要，需求', category: '形容', emoji: '🙋' },
  { char: '必', pinyin: 'bì', meaning: '必定，必须', category: '形容', emoji: '💯' },
  { char: '当', pinyin: 'dāng', meaning: '应当，担任', category: '形容', emoji: '👤' },
  { char: '若', pinyin: 'ruò', meaning: '如果，好像', category: '形容', emoji: '🤔' },
  { char: '或', pinyin: 'huò', meaning: '或者，也许', category: '形容', emoji: '🔄' },

  { char: '虽', pinyin: 'suī', meaning: '虽然', category: '形容', emoji: '↩️' },
  { char: '因', pinyin: 'yīn', meaning: '因为，原因', category: '形容', emoji: '❓' },
  { char: '果', pinyin: 'guǒ', meaning: '结果，果实', category: '形容', emoji: '🍎' },
  { char: '即', pinyin: 'jí', meaning: '就是，立即', category: '形容', emoji: '⚡' },
  { char: '则', pinyin: 'zé', meaning: '就，那么', category: '形容', emoji: '➡️' },
  { char: '且', pinyin: 'qiě', meaning: '而且，并且', category: '形容', emoji: '➕' },
  { char: '并', pinyin: 'bìng', meaning: '并且，合并', category: '形容', emoji: '🔗' },
  { char: '而', pinyin: 'ér', meaning: '而且，但是', category: '形容', emoji: '↩️' },
  { char: '于', pinyin: 'yú', meaning: '在，对，到', category: '形容', emoji: '📍' },
  { char: '与', pinyin: 'yǔ', meaning: '和，跟', category: '形容', emoji: '🤝' },

  { char: '及', pinyin: 'jí', meaning: '和，以及', category: '形容', emoji: '➕' },
  { char: '等', pinyin: 'děng', meaning: '等待，等级', category: '动作', emoji: '⏳' },
  { char: '像', pinyin: 'xiàng', meaning: '好像，类似', category: '形容', emoji: '🪞' },
  { char: '相', pinyin: 'xiāng', meaning: '互相，相貌', category: '形容', emoji: '🔄' },
  { char: '自', pinyin: 'zì', meaning: '自己，自然', category: '形容', emoji: '🙋' },
  { char: '己', pinyin: 'jǐ', meaning: '自己', category: '形容', emoji: '🙋' },
  { char: '各', pinyin: 'gè', meaning: '每个，各自', category: '形容', emoji: '👥' },
  { char: '每', pinyin: 'měi', meaning: '每一个', category: '形容', emoji: '🔢' },
  { char: '某', pinyin: 'mǒu', meaning: '某个，有的', category: '形容', emoji: '❓' },
  { char: '另', pinyin: 'lìng', meaning: '另外，其他', category: '形容', emoji: '🔄' },

  // ===== 第101-120关 =====
  { char: '原', pinyin: 'yuán', meaning: '原来，原因', category: '形容', emoji: '🔙' },
  { char: '现', pinyin: 'xiàn', meaning: '现在，出现', category: '时间', emoji: '⏰' },
  { char: '实', pinyin: 'shí', meaning: '真实，实际', category: '形容', emoji: '💯' },
  { char: '虚', pinyin: 'xū', meaning: '空的，不真实', category: '形容', emoji: '🌫️' },
  { char: '空', pinyin: 'kōng', meaning: '里面没有东西', category: '形容', emoji: '⭕' },
  { char: '满', pinyin: 'mǎn', meaning: '全部装满', category: '形容', emoji: '💯' },
  { char: '整', pinyin: 'zhěng', meaning: '完整，整齐', category: '形容', emoji: '✅' },
  { char: '齐', pinyin: 'qí', meaning: '整齐，一齐', category: '形容', emoji: '📏' },
  { char: '杂', pinyin: 'zá', meaning: '多种混合', category: '形容', emoji: '🔀' },
  { char: '纯', pinyin: 'chún', meaning: '纯净，不掺杂质', category: '形容', emoji: '💎' },

  { char: '善', pinyin: 'shàn', meaning: '善良，善于', category: '形容', emoji: '😇' },
  { char: '恶', pinyin: 'è', meaning: '坏的，凶恶', category: '形容', emoji: '😈' },
  { char: '强', pinyin: 'qiáng', meaning: '有力，强大', category: '形容', emoji: '💪' },
  { char: '弱', pinyin: 'ruò', meaning: '没力，虚弱', category: '形容', emoji: '😟' },
  { char: '胖', pinyin: 'pàng', meaning: '身体肥壮', category: '形容', emoji: '🐻' },
  { char: '瘦', pinyin: 'shòu', meaning: '身体细瘦', category: '形容', emoji: '🦒' },
  { char: '勇', pinyin: 'yǒng', meaning: '勇敢，有胆量', category: '形容', emoji: '🦁' },
  { char: '敢', pinyin: 'gǎn', meaning: '有勇气做', category: '动作', emoji: '💪' },
  { char: '怕', pinyin: 'pà', meaning: '害怕', category: '情绪', emoji: '😨' },
  { char: '惊', pinyin: 'jīng', meaning: '吃惊，惊讶', category: '情绪', emoji: '😲' },

  { char: '静', pinyin: 'jìng', meaning: '安静，没有声音', category: '形容', emoji: '🤫' },
  { char: '闹', pinyin: 'nào', meaning: '吵闹，热闹', category: '形容', emoji: '📢' },
  { char: '净', pinyin: 'jìng', meaning: '干净', category: '形容', emoji: '✨' },
  { char: '脏', pinyin: 'zāng', meaning: '不干净', category: '形容', emoji: '🧹' },
  { char: '稳', pinyin: 'wěn', meaning: '稳定，稳妥', category: '形容', emoji: '🧘' },
  { char: '险', pinyin: 'xiǎn', meaning: '危险，不安全', category: '形容', emoji: '⚠️' },
  { char: '奇', pinyin: 'qí', meaning: '奇怪，奇妙', category: '形容', emoji: '🤩' },
  { char: '妙', pinyin: 'miào', meaning: '美妙，巧妙', category: '形容', emoji: '✨' },
  { char: '趣', pinyin: 'qù', meaning: '有趣，兴趣', category: '情绪', emoji: '😄' },
  { char: '苦', pinyin: 'kǔ', meaning: '辛苦，痛苦', category: '形容', emoji: '😫' },

  { char: '累', pinyin: 'lèi', meaning: '疲劳，劳累', category: '形容', emoji: '😴' },
  { char: '闲', pinyin: 'xián', meaning: '空闲，没事做', category: '形容', emoji: '☕' },
  { char: '忙', pinyin: 'máng', meaning: '忙碌，有很多事', category: '形容', emoji: '🏃' },
  { char: '懒', pinyin: 'lǎn', meaning: '不爱动，不勤快', category: '形容', emoji: '🦥' },
  { char: '勤', pinyin: 'qín', meaning: '勤劳，勤奋', category: '形容', emoji: '💪' },
  { char: '聪', pinyin: 'cōng', meaning: '聪明，智力好', category: '形容', emoji: '🧠' },
  { char: '明', pinyin: 'míng', meaning: '明亮，明白', category: '形容', emoji: '💡' },
  { char: '智', pinyin: 'zhì', meaning: '智慧，聪明', category: '形容', emoji: '🧠' },
  { char: '笨', pinyin: 'bèn', meaning: '不聪明', category: '形容', emoji: '🤔' },
  { char: '愚', pinyin: 'yú', meaning: '愚蠢，笨', category: '形容', emoji: '🙈' },

  { char: '优', pinyin: 'yōu', meaning: '优秀，优良', category: '形容', emoji: '🏆' },
  { char: '良', pinyin: 'liáng', meaning: '良好，好', category: '形容', emoji: '⭐' },
  { char: '差', pinyin: 'chà', meaning: '不好，相差', category: '形容', emoji: '📉' },
  { char: '普', pinyin: 'pǔ', meaning: '普通，普遍', category: '形容', emoji: '👤' },
  { char: '特', pinyin: 'tè', meaning: '特别，特殊', category: '形容', emoji: '⭐' },
  { char: '贵', pinyin: 'guì', meaning: '价格高，珍贵', category: '形容', emoji: '💎' },
  { char: '贱', pinyin: 'jiàn', meaning: '价格低', category: '形容', emoji: '💸' },
  { char: '富', pinyin: 'fù', meaning: '有钱，富有', category: '形容', emoji: '💰' },
  { char: '贫', pinyin: 'pín', meaning: '没有钱，贫穷', category: '形容', emoji: '😢' },
  { char: '穷', pinyin: 'qióng', meaning: '没钱，穷困', category: '形容', emoji: '😿' },

  // ===== 第121-160关：较难汉字 =====
  { char: '影', pinyin: 'yǐng', meaning: '影子，电影', category: '自然', emoji: '👤' },
  { char: '像', pinyin: 'xiàng', meaning: '画像，照片', category: '物品', emoji: '🖼️' },
  { char: '梦', pinyin: 'mèng', meaning: '做梦，梦想', category: '动作', emoji: '💭' },
  { char: '醒', pinyin: 'xǐng', meaning: '醒来，清醒', category: '动作', emoji: '👀' },
  { char: '幻', pinyin: 'huàn', meaning: '虚幻，幻想', category: '形容', emoji: '🔮' },
  { char: '灵', pinyin: 'líng', meaning: '灵活，灵巧', category: '形容', emoji: '✨' },
  { char: '魂', pinyin: 'hún', meaning: '灵魂', category: '形容', emoji: '👻' },
  { char: '魄', pinyin: 'pò', meaning: '气魄，胆量', category: '形容', emoji: '💪' },
  { char: '精', pinyin: 'jīng', meaning: '精神，精致', category: '形容', emoji: '⭐' },
  { char: '神', pinyin: 'shén', meaning: '神奇，精神', category: '形容', emoji: '✨' },

  { char: '境', pinyin: 'jìng', meaning: '环境，境界', category: '形容', emoji: '🏞️' },
  { char: '幕', pinyin: 'mù', meaning: '幕布，屏幕', category: '物品', emoji: '🎬' },
  { char: '陪', pinyin: 'péi', meaning: '陪伴，陪同', category: '动作', emoji: '🤝' },
  { char: '随', pinyin: 'suí', meaning: '跟随，随意', category: '动作', emoji: '🚶' },
  { char: '创', pinyin: 'chuàng', meaning: '创造，创新', category: '动作', emoji: '💡' },
  { char: '造', pinyin: 'zào', meaning: '制造，建造', category: '动作', emoji: '🏗️' },
  { char: '修', pinyin: 'xiū', meaning: '修理，修建', category: '动作', emoji: '🔧' },
  { char: '建', pinyin: 'jiàn', meaning: '建设，建造', category: '动作', emoji: '🏗️' },
  { char: '设', pinyin: 'shè', meaning: '设置，设立', category: '动作', emoji: '⚙️' },
  { char: '装', pinyin: 'zhuāng', meaning: '安装，装扮', category: '动作', emoji: '🔧' },

  { char: '源', pinyin: 'yuán', meaning: '来源，源头', category: '自然', emoji: '💧' },
  { char: '流', pinyin: 'liú', meaning: '流动，河流', category: '自然', emoji: '🌊' },
  { char: '滴', pinyin: 'dī', meaning: '水滴，一滴', category: '自然', emoji: '💧' },
  { char: '涌', pinyin: 'yǒng', meaning: '涌出，涌现', category: '自然', emoji: '🌊' },
  { char: '涛', pinyin: 'tāo', meaning: '波涛，大浪', category: '自然', emoji: '🌊' },
  { char: '浪', pinyin: 'làng', meaning: '波浪', category: '自然', emoji: '🌊' },
  { char: '冰', pinyin: 'bīng', meaning: '水结成的固体', category: '自然', emoji: '🧊' },
  { char: '霜', pinyin: 'shuāng', meaning: '近地面的白色冰晶', category: '天气', emoji: '❄️' },
  { char: '雾', pinyin: 'wù', meaning: '水汽凝结的白色物', category: '天气', emoji: '🌫️' },
  { char: '露', pinyin: 'lù', meaning: '凝结在叶上的水珠', category: '天气', emoji: '💧' },

  { char: '猎', pinyin: 'liè', meaning: '打猎，捕捉', category: '动作', emoji: '🏹' },
  { char: '牧', pinyin: 'mù', meaning: '放牧，牧民', category: '社会', emoji: '🐄' },
  { char: '渔', pinyin: 'yú', meaning: '捕鱼，打鱼', category: '社会', emoji: '🎣' },
  { char: '耕', pinyin: 'gēng', meaning: '耕田，种地', category: '动作', emoji: '🌾' },
  { char: '织', pinyin: 'zhī', meaning: '编织，纺织', category: '动作', emoji: '🧵' },
  { char: '缝', pinyin: 'féng', meaning: '缝合，缝补', category: '动作', emoji: '🧵' },
  { char: '烧', pinyin: 'shāo', meaning: '燃烧，加热', category: '动作', emoji: '🔥' },
  { char: '烤', pinyin: 'kǎo', meaning: '用火烘烤', category: '动作', emoji: '🔥' },
  { char: '煮', pinyin: 'zhǔ', meaning: '用水加热食物', category: '动作', emoji: '🍲' },
  { char: '蒸', pinyin: 'zhēng', meaning: '用蒸汽加热', category: '动作', emoji: '♨️' },

  { char: '倾', pinyin: 'qīng', meaning: '倾斜，倒出', category: '动作', emoji: '↗️' },
  { char: '覆', pinyin: 'fù', meaning: '翻倒，覆盖', category: '动作', emoji: '🔄' },
  { char: '隐', pinyin: 'yǐn', meaning: '隐藏，不显露', category: '动作', emoji: '🙈' },
  { char: '现', pinyin: 'xiàn', meaning: '出现，显现', category: '动作', emoji: '👀' },
  { char: '避', pinyin: 'bì', meaning: '躲避，避开', category: '动作', emoji: '🏃' },
  { char: '逃', pinyin: 'táo', meaning: '逃跑，逃离', category: '动作', emoji: '🏃' },
  { char: '追', pinyin: 'zhuī', meaning: '追赶，追求', category: '动作', emoji: '🏃' },
  { char: '赶', pinyin: 'gǎn', meaning: '赶紧，追赶', category: '动作', emoji: '🏃' },
  { char: '赴', pinyin: 'fù', meaning: '前往，参加', category: '动作', emoji: '🚶' },
  { char: '途', pinyin: 'tú', meaning: '路途，旅途', category: '场所', emoji: '🗺️' },

  // ===== 第121-130关：更多进阶字 =====
  { char: '容', pinyin: 'róng', meaning: '容貌，容纳', category: '形容', emoji: '😊' },
  { char: '貌', pinyin: 'mào', meaning: '相貌，外貌', category: '形容', emoji: '🪞' },
  { char: '态', pinyin: 'tài', meaning: '态度，状态', category: '形容', emoji: '👤' },
  { char: '势', pinyin: 'shì', meaning: '势力，形势', category: '形容', emoji: '📈' },
  { char: '服', pinyin: 'fú', meaning: '衣服，服从', category: '物品', emoji: '👔' },
  { char: '装', pinyin: 'zhuāng', meaning: '穿着，装饰', category: '动作', emoji: '👔' },
  { char: '饰', pinyin: 'shì', meaning: '装饰，饰品', category: '物品', emoji: '💎' },
  { char: '冠', pinyin: 'guàn', meaning: '帽子，冠军', category: '物品', emoji: '👑' },
  { char: '幅', pinyin: 'fú', meaning: '宽度，一幅画', category: '形容', emoji: '🖼️' },
  { char: '度', pinyin: 'dù', meaning: '程度，度量', category: '形容', emoji: '📏' },

  { char: '察', pinyin: 'chá', meaning: '观察，查看', category: '动作', emoji: '👀' },
  { char: '观', pinyin: 'guān', meaning: '观看，观察', category: '动作', emoji: '👁️' },
  { char: '赏', pinyin: 'shǎng', meaning: '欣赏，奖赏', category: '动作', emoji: '🏆' },
  { char: '鉴', pinyin: 'jiàn', meaning: '鉴定，镜子', category: '动作', emoji: '🪞' },
  { char: '评', pinyin: 'píng', meaning: '评价，评论', category: '动作', emoji: '📝' },
  { char: '判', pinyin: 'pàn', meaning: '判断，判决', category: '动作', emoji: '⚖️' },
  { char: '决', pinyin: 'jué', meaning: '决定，解决', category: '动作', emoji: '✅' },
  { char: '断', pinyin: 'duàn', meaning: '判断，折断', category: '动作', emoji: '✂️' },
  { char: '选', pinyin: 'xuǎn', meaning: '选择，挑选', category: '动作', emoji: '👆' },
  { char: '挑', pinyin: 'tiāo', meaning: '挑选，挑起', category: '动作', emoji: '☝️' },

  { char: '抬', pinyin: 'tái', meaning: '共同举起', category: '动作', emoji: '🤲' },
  { char: '举', pinyin: 'jǔ', meaning: '往上托', category: '动作', emoji: '🙌' },
  { char: '扬', pinyin: 'yáng', meaning: '高举，传播', category: '动作', emoji: '旗帜' },
  { char: '扔', pinyin: 'rēng', meaning: '投掷，丢弃', category: '动作', emoji: '🗑️' },
  { char: '抛', pinyin: 'pāo', meaning: '投掷，抛出', category: '动作', emoji: '🤾' },
  { char: '投', pinyin: 'tóu', meaning: '投入，投掷', category: '动作', emoji: '🏀' },
  { char: '摔', pinyin: 'shuāi', meaning: '跌倒，摔落', category: '动作', emoji: '😱' },
  { char: '撞', pinyin: 'zhuàng', meaning: '猛烈碰击', category: '动作', emoji: '💥' },
  { char: '碰', pinyin: 'pèng', meaning: '接触，碰到', category: '动作', emoji: '👋' },
  { char: '触', pinyin: 'chù', meaning: '接触，触摸', category: '动作', emoji: '👆' },

  { char: '抵', pinyin: 'dǐ', meaning: '抵抗，抵达', category: '动作', emoji: '🛡️' },
  { char: '挡', pinyin: 'dǎng', meaning: '阻挡，挡住', category: '动作', emoji: '🛑' },
  { char: '拦', pinyin: 'lán', meaning: '阻挡，拦截', category: '动作', emoji: '🚫' },
  { char: '阻', pinyin: 'zǔ', meaning: '阻碍，阻挡', category: '动作', emoji: '🛑' },
  { char: '围', pinyin: 'wéi', meaning: '包围，围绕', category: '动作', emoji: '🔄' },
  { char: '困', pinyin: 'kùn', meaning: '困难，被困', category: '形容', emoji: '😓' },
  { char: '束', pinyin: 'shù', meaning: '捆住，约束', category: '动作', emoji: '🎀' },
  { char: '绑', pinyin: 'bǎng', meaning: '用绳系住', category: '动作', emoji: '🪢' },
  { char: '系', pinyin: 'xì', meaning: '打结，系上', category: '动作', emoji: '🎀' },
  { char: '解', pinyin: 'jiě', meaning: '解开，解答', category: '动作', emoji: '🔓' },

  { char: '翻', pinyin: 'fān', meaning: '翻转，翻书', category: '动作', emoji: '🔄' },
  { char: '转', pinyin: 'zhuǎn', meaning: '改变方向', category: '动作', emoji: '↩️' },
  { char: '旋', pinyin: 'xuán', meaning: '旋转，回旋', category: '动作', emoji: '🌀' },
  { char: '摇', pinyin: 'yáo', meaning: '来回摆动', category: '动作', emoji: '📳' },
  { char: '摆', pinyin: 'bǎi', meaning: '放置，摇摆', category: '动作', emoji: '↔️' },
  { char: '挥', pinyin: 'huī', meaning: '挥手，挥动', category: '动作', emoji: '👋' },
  { char: '擦', pinyin: 'cā', meaning: '摩擦，擦拭', category: '动作', emoji: '🧹' },
  { char: '抹', pinyin: 'mǒ', meaning: '擦拭，涂抹', category: '动作', emoji: '🧽' },
  { char: '扫', pinyin: 'sǎo', meaning: '打扫，扫除', category: '动作', emoji: '🧹' },
  { char: '刷', pinyin: 'shuā', meaning: '刷洗，刷子', category: '动作', emoji: '🪥' },

  { char: '洗', pinyin: 'xǐ', meaning: '用水清洁', category: '动作', emoji: '🚿' },
  { char: '浴', pinyin: 'yù', meaning: '洗澡，沐浴', category: '动作', emoji: '🛁' },
  { char: '净', pinyin: 'jìng', meaning: '干净，净化', category: '形容', emoji: '✨' },
  { char: '漂', pinyin: 'piāo', meaning: '浮在水面，漂亮', category: '形容', emoji: '🌊' },
  { char: '浮', pinyin: 'fú', meaning: '飘浮在水面', category: '动作', emoji: '🎈' },
  { char: '沉', pinyin: 'chén', meaning: '往下落，沉入水底', category: '动作', emoji: '⬇️' },
  { char: '漂', pinyin: 'piǎo', meaning: '漂亮，好看', category: '形容', emoji: '✨' },
  { char: '亮', pinyin: 'liàng', meaning: '发光，明亮', category: '形容', emoji: '💡' },
  { char: '暗', pinyin: 'àn', meaning: '黑暗，不明亮', category: '形容', emoji: '🌑' },
  { char: '阴', pinyin: 'yīn', meaning: '阴天，背光', category: '天气', emoji: '☁️' },

  { char: '晴', pinyin: 'qíng', meaning: '天气晴朗', category: '天气', emoji: '☀️' },
  { char: '暖', pinyin: 'nuǎn', meaning: '温暖，暖和', category: '形容', emoji: '☀️' },
  { char: '凉', pinyin: 'liáng', meaning: '凉爽，微冷', category: '形容', emoji: '🌬️' },
  { char: '温', pinyin: 'wēn', meaning: '温度，温和', category: '形容', emoji: '🌡️' },
  { char: '暴', pinyin: 'bào', meaning: '突然，猛烈', category: '形容', emoji: '⛈️' },
  { char: '雷', pinyin: 'léi', meaning: '天上的响声', category: '天气', emoji: '⛈️' },
  { char: '闪', pinyin: 'shǎn', meaning: '闪电，闪开', category: '天气', emoji: '⚡' },
  { char: '虹', pinyin: 'hóng', meaning: '雨后的彩虹', category: '自然', emoji: '🌈' },
  { char: '潮', pinyin: 'cháo', meaning: '潮水，潮湿', category: '自然', emoji: '🌊' },
  { char: '洪', pinyin: 'hóng', meaning: '大水，洪水', category: '自然', emoji: '🌊' },

  { char: '灾', pinyin: 'zāi', meaning: '灾害，灾难', category: '自然', emoji: '⚠️' },
  { char: '荒', pinyin: 'huāng', meaning: '荒芜，荒凉', category: '形容', emoji: '🏜️' },
  { char: '旱', pinyin: 'hàn', meaning: '缺水，干旱', category: '天气', emoji: '☀️' },
  { char: '涝', pinyin: 'lào', meaning: '水淹，涝灾', category: '天气', emoji: '🌧️' },
  { char: '疫', pinyin: 'yì', meaning: '瘟疫，传染病', category: '社会', emoji: '🏥' },
  { char: '病', pinyin: 'bìng', meaning: '生病，疾病', category: '社会', emoji: '🤒' },
  { char: '痛', pinyin: 'tòng', meaning: '疼痛，痛苦', category: '形容', emoji: '😣' },
  { char: '伤', pinyin: 'shāng', meaning: '受伤，伤害', category: '形容', emoji: '🩹' },
  { char: '愈', pinyin: 'yù', meaning: '痊愈，愈合', category: '形容', emoji: '💚' },
  { char: '治', pinyin: 'zhì', meaning: '治疗，治理', category: '动作', emoji: '💊' },

  { char: '药', pinyin: 'yào', meaning: '治病的药品', category: '物品', emoji: '💊' },
  { char: '针', pinyin: 'zhēn', meaning: '缝衣针，打针', category: '物品', emoji: '💉' },
  { char: '术', pinyin: 'shù', meaning: '技术，方法', category: '形容', emoji: '🔬' },
  { char: '医', pinyin: 'yī', meaning: '医生，医学', category: '人物', emoji: '👨‍⚕️' },
  { char: '护', pinyin: 'hù', meaning: '保护，护理', category: '动作', emoji: '🛡️' },
  { char: '康', pinyin: 'kāng', meaning: '健康，安康', category: '形容', emoji: '💚' },
  { char: '健', pinyin: 'jiàn', meaning: '强健，健康', category: '形容', emoji: '💪' },
  { char: '寿', pinyin: 'shòu', meaning: '寿命，长寿', category: '形容', emoji: '🎂' },
  { char: '险', pinyin: 'xiǎn', meaning: '危险，险要', category: '形容', emoji: '⚠️' },
  { char: '救', pinyin: 'jiù', meaning: '救助，拯救', category: '动作', emoji: '🆘' },

  { char: '助', pinyin: 'zhù', meaning: '帮助，协助', category: '动作', emoji: '🤝' },
  { char: '援', pinyin: 'yuán', meaning: '援助，支援', category: '动作', emoji: '🆘' },
  { char: '帮', pinyin: 'bāng', meaning: '帮忙，帮助', category: '动作', emoji: '🤝' },
  { char: '恩', pinyin: 'ēn', meaning: '恩情，感恩', category: '情绪', emoji: '🙏' },
  { char: '谢', pinyin: 'xiè', meaning: '感谢，道谢', category: '动作', emoji: '🙏' },
  { char: '礼', pinyin: 'lǐ', meaning: '礼物，礼貌', category: '社会', emoji: '🎁' },
  { char: '仪', pinyin: 'yí', meaning: '仪式，礼仪', category: '社会', emoji: '🎩' },
  { char: '节', pinyin: 'jié', meaning: '节日，节俭', category: '时间', emoji: '🎊' },
  { char: '庆', pinyin: 'qìng', meaning: '庆祝，庆贺', category: '动作', emoji: '🎉' },
  { char: '祝', pinyin: 'zhù', meaning: '祝愿，祝福', category: '动作', emoji: '🎉' },

  { char: '贺', pinyin: 'hè', meaning: '祝贺，道贺', category: '动作', emoji: '🎊' },
  { char: '敬', pinyin: 'jìng', meaning: '尊敬，敬礼', category: '动作', emoji: '🙇' },
  { char: '孝', pinyin: 'xiào', meaning: '孝顺父母', category: '社会', emoji: '👴' },
  { char: '忠', pinyin: 'zhōng', meaning: '忠诚，忠实', category: '形容', emoji: '❤️' },
  { char: '义', pinyin: 'yì', meaning: '正义，义气', category: '形容', emoji: '⚖️' },
  { char: '德', pinyin: 'dé', meaning: '品德，道德', category: '形容', emoji: '⭐' },
  { char: '诚', pinyin: 'chéng', meaning: '诚实，真诚', category: '形容', emoji: '🤝' },
  { char: '信', pinyin: 'xìn', meaning: '信用，信任', category: '形容', emoji: '✅' },
  { char: '耻', pinyin: 'chǐ', meaning: '羞耻，耻辱', category: '情绪', emoji: '😳' },
  { char: '荣', pinyin: 'róng', meaning: '光荣，荣誉', category: '形容', emoji: '🏆' },

  { char: '辱', pinyin: 'rǔ', meaning: '侮辱，耻辱', category: '形容', emoji: '😞' },
  { char: '卑', pinyin: 'bēi', meaning: '低下，自卑', category: '形容', emoji: '📉' },
  { char: '尊', pinyin: 'zūn', meaning: '尊重，尊敬', category: '动作', emoji: '🙇' },
  { char: '严', pinyin: 'yán', meaning: '严格，严厉', category: '形容', emoji: '📌' },
  { char: '厉', pinyin: 'lì', meaning: '厉害，严厉', category: '形容', emoji: '😤' },
  { char: '慈', pinyin: 'cí', meaning: '慈祥，慈爱', category: '形容', emoji: '😇' },
  { char: '善', pinyin: 'shàn', meaning: '善良，善意', category: '形容', emoji: '😇' },
  { char: '温', pinyin: 'wēn', meaning: '温柔，温和', category: '形容', emoji: '🌷' },
  { char: '柔', pinyin: 'róu', meaning: '柔软，温柔', category: '形容', emoji: '🌸' },
  { char: '刚', pinyin: 'gāng', meaning: '坚硬，刚强', category: '形容', emoji: '💪' },

  { char: '毅', pinyin: 'yì', meaning: '坚毅，毅力', category: '形容', emoji: '🏅' },
  { char: '忍', pinyin: 'rěn', meaning: '忍耐，忍受', category: '动作', emoji: '🧘' },
  { char: '耐', pinyin: 'nài', meaning: '耐烦，耐用', category: '形容', emoji: '💪' },
  { char: '恒', pinyin: 'héng', meaning: '恒心，持久', category: '形容', emoji: '♾️' },
  { char: '坚', pinyin: 'jiān', meaning: '坚固，坚定', category: '形容', emoji: '🧱' },
  { char: '固', pinyin: 'gù', meaning: '牢固，固定', category: '形容', emoji: '🧱' },
  { char: '牢', pinyin: 'láo', meaning: '牢固，牢房', category: '形容', emoji: '🔒' },
  { char: '稳', pinyin: 'wěn', meaning: '稳定，安稳', category: '形容', emoji: '⚖️' },
  { char: '妥', pinyin: 'tuǒ', meaning: '妥当，稳妥', category: '形容', emoji: '✅' },
  { char: '适', pinyin: 'shì', meaning: '合适，适当', category: '形容', emoji: '👍' },

  // ===== 第141-160关 =====
  { char: '均', pinyin: 'jūn', meaning: '均匀，平均', category: '形容', emoji: '⚖️' },
  { char: '匀', pinyin: 'yún', meaning: '均匀，匀称', category: '形容', emoji: '📐' },
  { char: '偏', pinyin: 'piān', meaning: '偏斜，偏旁', category: '形容', emoji: '↗️' },
  { char: '正', pinyin: 'zhèng', meaning: '端正，正确', category: '形容', emoji: '✅' },
  { char: '歪', pinyin: 'wāi', meaning: '不正，歪斜', category: '形容', emoji: '↩️' },
  { char: '齐', pinyin: 'qí', meaning: '整齐，一齐', category: '形容', emoji: '📏' },
  { char: '顺', pinyin: 'shùn', meaning: '顺利，顺从', category: '形容', emoji: '↘️' },
  { char: '逆', pinyin: 'nì', meaning: '相反，逆向', category: '形容', emoji: '↩️' },
  { char: '反', pinyin: 'fǎn', meaning: '反面，相反', category: '形容', emoji: '🔄' },
  { char: '倒', pinyin: 'dào', meaning: '倒下，倒转', category: '动作', emoji: '🔃' },

  { char: '纵', pinyin: 'zòng', meaning: '放纵，纵向', category: '形容', emoji: '↕️' },
  { char: '横', pinyin: 'héng', meaning: '横向，蛮横', category: '形容', emoji: '↔️' },
  { char: '竖', pinyin: 'shù', meaning: '竖立，直立', category: '形容', emoji: '⬆️' },
  { char: '直', pinyin: 'zhí', meaning: '笔直，直接', category: '形容', emoji: '📏' },
  { char: '弯', pinyin: 'wān', meaning: '弯曲，转弯', category: '形容', emoji: '↪️' },
  { char: '曲', pinyin: 'qǔ', meaning: '弯曲，歌曲', category: '形容', emoji: '🎵' },
  { char: '折', pinyin: 'zhé', meaning: '折叠，折断', category: '动作', emoji: '📐' },
  { char: '叠', pinyin: 'dié', meaning: '重叠，折叠', category: '动作', emoji: '📄' },
  { char: '层', pinyin: 'céng', meaning: '层次，楼层', category: '形容', emoji: '🏢' },
  { char: '阶', pinyin: 'jiē', meaning: '台阶，阶段', category: '形容', emoji: '🪜' },

  { char: '梯', pinyin: 'tī', meaning: '梯子，阶梯', category: '物品', emoji: '🪜' },
  { char: '塔', pinyin: 'tǎ', meaning: '高耸的建筑', category: '建筑', emoji: '🗼' },
  { char: '阁', pinyin: 'gé', meaning: '楼阁，阁楼', category: '建筑', emoji: '🏯' },
  { char: '殿', pinyin: 'diàn', meaning: '宫殿，大殿', category: '建筑', emoji: '🏛️' },
  { char: '宫', pinyin: 'gōng', meaning: '宫殿，皇宫', category: '建筑', emoji: '🏯' },
  { char: '堂', pinyin: 'táng', meaning: '厅堂，课堂', category: '建筑', emoji: '🏫' },
  { char: '馆', pinyin: 'guǎn', meaning: '场馆，图书馆', category: '建筑', emoji: '🏛️' },
  { char: '院', pinyin: 'yuàn', meaning: '院子，医院', category: '建筑', emoji: '🏠' },
  { char: '寺', pinyin: 'sì', meaning: '寺庙，寺院', category: '建筑', emoji: '⛩️' },
  { char: '庙', pinyin: 'miào', meaning: '庙宇，寺庙', category: '建筑', emoji: '⛩️' },

  { char: '坛', pinyin: 'tán', meaning: '平台，讲坛', category: '建筑', emoji: '🏟️' },
  { char: '碑', pinyin: 'bēi', meaning: '石碑，纪念碑', category: '建筑', emoji: '🪦' },
  { char: '柱', pinyin: 'zhù', meaning: '柱子，支撑', category: '建筑', emoji: '🏛️' },
  { char: '墙', pinyin: 'qiáng', meaning: '墙壁', category: '建筑', emoji: '🧱' },
  { char: '瓦', pinyin: 'wǎ', meaning: '瓦片，盖房用', category: '建筑', emoji: '🏠' },
  { char: '砖', pinyin: 'zhuān', meaning: '砖头，砌墙用', category: '建筑', emoji: '🧱' },
  { char: '泥', pinyin: 'ní', meaning: '泥巴，泥土', category: '自然', emoji: '🟤' },
  { char: '沙', pinyin: 'shā', meaning: '细小的石粒', category: '自然', emoji: '🏖️' },
  { char: '尘', pinyin: 'chén', meaning: '灰尘，尘土', category: '自然', emoji: '🌫️' },
  { char: '灰', pinyin: 'huī', meaning: '灰色，灰烬', category: '颜色', emoji: '⚪' },

  { char: '烟', pinyin: 'yān', meaning: '烟雾，烟火', category: '自然', emoji: '💨' },
  { char: '焰', pinyin: 'yàn', meaning: '火焰', category: '自然', emoji: '🔥' },
  { char: '炭', pinyin: 'tàn', meaning: '木炭，煤炭', category: '物品', emoji: '⚫' },
  { char: '油', pinyin: 'yóu', meaning: '食用油，汽油', category: '物品', emoji: '🛢️' },
  { char: '盐', pinyin: 'yán', meaning: '调味品', category: '食物', emoji: '🧂' },
  { char: '酱', pinyin: 'jiàng', meaning: '酱油，酱料', category: '食物', emoji: '🫙' },
  { char: '醋', pinyin: 'cù', meaning: '酸味调料', category: '食物', emoji: '🍶' },
  { char: '酱', pinyin: 'jiàng', meaning: '酱料', category: '食物', emoji: '🫙' },
  { char: '饼', pinyin: 'bǐng', meaning: '饼类食物', category: '食物', emoji: '🫓' },
  { char: '糕', pinyin: 'gāo', meaning: '糕点食品', category: '食物', emoji: '🍰' },

  { char: '粽', pinyin: 'zòng', meaning: '粽子，端午食品', category: '食物', emoji: '🎋' },
  { char: '饺', pinyin: 'jiǎo', meaning: '饺子，面食', category: '食物', emoji: '🥟' },
  { char: '汤', pinyin: 'tāng', meaning: '汤水，热汤', category: '食物', emoji: '🍲' },
  { char: '粥', pinyin: 'zhōu', meaning: '粥，稀饭', category: '食物', emoji: '🥣' },
  { char: '饼', pinyin: 'bǐng', meaning: '饼，圆形食品', category: '食物', emoji: '🫓' },
  { char: '馒', pinyin: 'mán', meaning: '馒头', category: '食物', emoji: '🍞' },
  { char: '笼', pinyin: 'lóng', meaning: '笼子，蒸笼', category: '物品', emoji: '🫙' },
  { char: '筛', pinyin: 'shāi', meaning: '筛子，过滤', category: '物品', emoji: '🔍' },
  { char: '碗', pinyin: 'wǎn', meaning: '吃饭用的碗', category: '物品', emoji: '🥣' },
  { char: '盘', pinyin: 'pán', meaning: '盘子，棋盘', category: '物品', emoji: '🍽️' },

  { char: '盆', pinyin: 'pén', meaning: '盆子，花盆', category: '物品', emoji: '🪴' },
  { char: '瓶', pinyin: 'píng', meaning: '瓶子', category: '物品', emoji: '🍾' },
  { char: '罐', pinyin: 'guàn', meaning: '罐子', category: '物品', emoji: '🫙' },
  { char: '壶', pinyin: 'hú', meaning: '水壶，茶壶', category: '物品', emoji: '🫖' },
  { char: '杯', pinyin: 'bēi', meaning: '杯子', category: '物品', emoji: '🍵' },
  { char: '盏', pinyin: 'zhǎn', meaning: '小杯子，灯盏', category: '物品', emoji: '🏮' },
  { char: '锅', pinyin: 'guō', meaning: '炒菜的锅', category: '物品', emoji: '🍳' },
  { char: '灶', pinyin: 'zào', meaning: '厨房灶台', category: '物品', emoji: '🔥' },
  { char: '炉', pinyin: 'lú', meaning: '火炉，炉子', category: '物品', emoji: '🔥' },
  { char: '扇', pinyin: 'shàn', meaning: '扇子，电扇', category: '物品', emoji: '🪭' },

  { char: '锁', pinyin: 'suǒ', meaning: '锁住，开锁', category: '物品', emoji: '🔒' },
  { char: '钥', pinyin: 'yào', meaning: '钥匙', category: '物品', emoji: '🔑' },
  { char: '剪', pinyin: 'jiǎn', meaning: '剪刀，剪断', category: '物品', emoji: '✂️' },
  { char: '刀', pinyin: 'dāo', meaning: '刀子，刀具', category: '物品', emoji: '🔪' },
  { char: '枪', pinyin: 'qiāng', meaning: '枪械', category: '物品', emoji: '🔫' },
  { char: '箭', pinyin: 'jiàn', meaning: '弓箭，箭头', category: '物品', emoji: '🏹' },
  { char: '弓', pinyin: 'gōng', meaning: '射箭用的弓', category: '物品', emoji: '🏹' },
  { char: '弹', pinyin: 'dàn', meaning: '子弹，弹弓', category: '物品', emoji: '🎯' },
  { char: '炮', pinyin: 'pào', meaning: '大炮，鞭炮', category: '物品', emoji: '🧨' },
  { char: '旗', pinyin: 'qí', meaning: '旗帜，国旗', category: '物品', emoji: '🚩' },

  { char: '鼓', pinyin: 'gǔ', meaning: '打鼓，鼓', category: '物品', emoji: '🥁' },
  { char: '钟', pinyin: 'zhōng', meaning: '钟表，敲钟', category: '物品', emoji: '🔔' },
  { char: '铃', pinyin: 'líng', meaning: '铃铛，按铃', category: '物品', emoji: '🔔' },
  { char: '筝', pinyin: 'zhēng', meaning: '风筝，古筝', category: '物品', emoji: '🪁' },
  { char: '琴', pinyin: 'qín', meaning: '钢琴，琴声', category: '物品', emoji: '🎹' },
  { char: '笛', pinyin: 'dí', meaning: '笛子，吹笛', category: '物品', emoji: '🎵' },
  { char: '箫', pinyin: 'xiāo', meaning: '箫，吹奏乐器', category: '物品', emoji: '🎵' },
  { char: '棋', pinyin: 'qí', meaning: '下棋，象棋', category: '物品', emoji: '♟️' },
  { char: '牌', pinyin: 'pái', meaning: '扑克牌，门牌', category: '物品', emoji: '🃏' },
  { char: '球', pinyin: 'qiú', meaning: '球类运动', category: '物品', emoji: '⚽' },

  { char: '网', pinyin: 'wǎng', meaning: '鱼网，上网', category: '物品', emoji: '🕸️' },
  { char: '绳', pinyin: 'shéng', meaning: '绳子', category: '物品', emoji: '🪢' },
  { char: '线', pinyin: 'xiàn', meaning: '线条，丝线', category: '物品', emoji: '🧵' },
  { char: '针', pinyin: 'zhēn', meaning: '针，缝针', category: '物品', emoji: '📌' },
  { char: '钩', pinyin: 'gōu', meaning: '钩子，挂钩', category: '物品', emoji: '🪝' },
  { char: '环', pinyin: 'huán', meaning: '圆环，环节', category: '物品', emoji: '⭕' },
  { char: '圈', pinyin: 'quān', meaning: '圆圈，圈子', category: '物品', emoji: '⭕' },
  { char: '框', pinyin: 'kuàng', meaning: '框架，边框', category: '物品', emoji: '🖼️' },
  { char: '匣', pinyin: 'xiá', meaning: '小盒子', category: '物品', emoji: '📦' },
  { char: '箱', pinyin: 'xiāng', meaning: '箱子，皮箱', category: '物品', emoji: '📦' },
];

// 获取总关卡数
function getTotalLevels() {
  return Math.ceil(HANZI_DATA.length / 10);
}

// 获取某一关的汉字
function getLevelData(level) {
  const start = (level - 1) * 10;
  const end = start + 10;
  return HANZI_DATA.slice(start, end);
}

// 获取形近字（用于生成干扰选项）
function getSimilarChars(char, count = 3) {
  const similar = [];
  // 按偏旁部首和字形相似度匹配
  const allChars = HANZI_DATA.map(h => h.char);
  // 简单实现：从字库中挑选相似字形
  for (const item of HANZI_DATA) {
    if (item.char !== char && !similar.includes(item.char)) {
      // 检查是否有相同偏旁或相似结构
      if (hasSimilarStructure(char, item.char)) {
        similar.push(item.char);
        if (similar.length >= count * 2) break;
      }
    }
  }
  // 如果相似字不够，随机补充
  if (similar.length < count) {
    for (const item of HANZI_DATA) {
      if (item.char !== char && !similar.includes(item.char)) {
        similar.push(item.char);
        if (similar.length >= count * 2) break;
      }
    }
  }
  // 随机选取
  return shuffleArray(similar).slice(0, count);
}

// 简单的字形相似度判断
function hasSimilarStructure(char1, char2) {
  // 比较unicode编码接近程度
  const diff = Math.abs(char1.charCodeAt(0) - char2.charCodeAt(0));
  return diff < 100;
}

// 洗牌算法
function shuffleArray(arr) {
  const shuffled = [...arr];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
